markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: forcommu
author: ""
email: 
name: ""
url: 
domain: 
all_categories: [
["android", "Android cat","/posts/android.html"], 
["program", "Program cat","/posts/program.html"],
["web", "Web cat","/posts/web.html"], 
["linux", "Linux cat","/posts/linux.html"],
["read", "Read cat","/posts/read.html"], 
["other", "Other cat","/posts/other.html"],
["about", "About cat","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
